#!/bin/bash

source "$HOME/.config/colors.sh"

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

MAX_SPACES=10

# create default maximum number of spaces 
$HOME/.config/yabai/create_spaces.sh

# load boarders
$HOME/.config/borders/bordersrc

# global settings
yabai -m config \
	mouse_follows_focus off \
	focus_follows_mouse off \
	window_origin_display default \
	window_placement second_child \
	window_zoom_persist off \
	window_shadow on \
	window_animation_duration 0.0 \
	window_opacity_duration 0.0 \
	active_window_opacity 1.0 \
	normal_window_opacity 1.0 \
	window_opacity off \
	insert_feedback_color 0xffd75f5f \
	split_ratio 0.50 \
	split_type auto \
	auto_balance off \
	top_padding 10 \
	bottom_padding 10 \
	left_padding 10 \
	right_padding 10 \
	window_gap 10 \
	layout bsp \
	mouse_modifier fn \
	mouse_action1 move \
	mouse_action2 resize \
	mouse_drop_action swap \
	external_bar all:48:0

yabai -m rule --add app="^(System Settings|System Information|Activity Monitor|FaceTime|Screen Sharing|Calculator|Stickies|TinkerTool|Progressive Downloader|Transmission|Airflow)$" manage=off

yabai -m signal --add event=window_created action="sketchybar -m --trigger window_change &> /dev/null"
yabai -m signal --add event=window_destroyed action="sketchybar -m --trigger window_change &> /dev/null"

echo "yabai configuration loaded.."
